### PR TITLE
Refactor `uprefs` and `prefs` to explicitly accept `context` instead of relying on `bpy.context`

### PR DESCRIPTION
**Pull request by Pluglug**
This pull request refactors the `uprefs` and `prefs` functions to explicitly accept a `context` argument instead of relying on the global `bpy.context`. These changes aim to reduce implicit dependencies and make error handling more explicit and predictable, aligning the codebase with best practices.

### Changes Included:
- **`uprefs(context=bpy.context)`**:
  - Retrieves user preferences from the specified `context`.
  - Raises `AttributeError` if user preferences cannot be accessed.
- **`prefs(context=bpy.context)`**:
  - Retrieves addon preferences from the specified `context`.
  - Raises `KeyError` if the addon preferences for `__package__` are not found.

### Benefits:
- Reduces reliance on global `bpy.context`.
- Improves error handling by making it explicit (`AttributeError` and `KeyError`).
- Enhances code clarity and maintainability.

### Additional Updates:
- Replaced legacy `None` checks for `prefs` with `try/except` blocks to align with the new behavior of `prefs()` always raising exceptions when preferences are unavailable.

While it is not necessary to replace all existing implementations immediately, I would like to adopt this approach in future developments to ensure consistency and maintainability.

### CODE REVIEW

**Comment by oRazeD** [comment]
`uprefs` and `prefs` should be renamed to something more legible, such as `get_user_preferences` and `get_addon_preferences` respectively. Otherwise, I don't see anything off about your changes. Did you run into both exception cases when testing?

**Comment by oRazeD** [comment]
@Pluglug Is this ready to be reviewed again?

**Comment by Pluglug** [comment]
Yes, at least I was able to confirm the output of KeyError. 
[blender/blender#130638](https://projects.blender.org/blender/blender/issues/130638)

I agree with you that it is a good idea to have a more descriptive function name, but I will take it down for now since it is not a priority change. Thanks for checking.

**Comment by oRazeD** [comment]
Just making sure you know this means none of your changes were committed?

**Pull request closed without merging**
